pay:
  ali:
#  阿里开发者Appid
    appId: 11213
    notifyUrl: http://b3b08aae.ngrok.io
    returnUrl: http://b3b08aae.ngrok.io
    url: https://openapi.alipaydev.com/gateway.do
    charset: UTF-8
    format: json
#    ali公钥
    aliPayPublicKey: classpath:ali/fromalipub.txt
#    我的私钥
    rsaPrivateKey: classpath:ali/alipri.txt
    logPath: D:/program/test/log/pay/alipay.log
    singType: RSA2
    payBackUrl: /pay/order/callback
  wechat:
    appID: 111111
    mchID: 123456789
    key: 231321312
    certStreams: classpath:pay/wechat/encryptpub.cer
    httpConnectTimeoutMs: 10000
    httpReadTimeoutMs: 10000
    charSet: UTF-8
    mchAppid: 34153453
server:
  port: 8083
