server:
  port: 8090
spring:
  application:
    name: service-stream-pub
  cloud:
    discovery:
        client:
          simple:
            local:
              service-id: service-stream-pub
    stream:
#kafka-start
#      kafka:
#        binder:
##Kafka的消息中间件服务器
#          brokers: localhost:9092
###Zookeeper的节点，如果集群，后面加,号分隔
##          zk-nodes: localhost:2181
##如果设置为false,就不会自动创建Topic 有可能你Topic还没创建就直接调用了。
#          auto-create-topics: true
##          auto-add-partitions: true
#kafka-end
      bindings:
#这里用stream给我们提供的默认output，后面会讲到自定义output
        output:
#消息发往的目的地,注意与接收端一致
          destination: stream-pub
#消息发送的格式，接收端不用指定格式，但是发送端要
          content-type: text/plain
#          自定义output
        myOutput:
          destination: stream-pub-my
          content-type: text/plain
#          自定义中转站的通道
        myTranceOutput:
          destination: stream-pub-trance-from
          content-type: text/plain
#          分组消息
        myGroupOutput:
          destination: stream-pub-group
          content-type: text/plain
#rabbitmq-start
      binders:
        local_rabbit:
          type: rabbit
          environment:
            spring:
              rabbitmq:
                host: localhost
                port: 5672
                username: guest
                password: guest
#rabbitmq-end
#          producer:
#          分区的主键，根据什么来分区，下面的payload.id只是一个对象的id用于做为Key，用来说明的。希望不要误解
#            partitionKeyExpression: payload.id
#            partitionCount: 2

eureka:
  instance:
      prefer-ip-address: true
  client:
    service-url:
      defaultZone: http://localhost:8765/eureka/
management:
  endpoints:
    web:
      exposure:
# SpringBootActuator监控暴露所有接口
        include: '*'
