server:
  port: 8084
spring:
  application:
    name: service-admin
  cloud:
    discovery:
      client:
        simple:
          local:
            service-id: service-admin
#链路追踪配置
    zipkin:
      base-url: http://localhost:9411
    sleuth:
      sampler:
        #链路信息全都要
        percentage: 1.0
#  安全验证
  security:
    user:
      name: admin
      password: admin
  boot:
    admin:
      client:
        username: admin
        password: admin
eureka:
  instance:
      prefer-ip-address: true
  client:
    service-url:
      defaultZone: http://localhost:8765/eureka/
management:
  endpoints:
    web:
      exposure:
        include: "*"

