server:
  port: 8082
spring:
  application:
    name: service-zipkin-server
  cloud:
    discovery:
      client:
        simple:
          local:
            service-id: service-zipkin-server
eureka:
  instance:
      prefer-ip-address: true
  client:
    service-url:
      defaultZone: http://localhost:8765/eureka/
zipkin:
  storage:
    StorageComponent: elasticsearch
    type: elasticsearch
    elasticsearch:
      hosts: http://192.168.2.60.9200
      cluster: NLX_ES
      index: mytest

